# Generated by Django 5.2.1 on 2025-06-01 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterpreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('twogislink', models.CharField(blank=True, max_length=255, null=True)),
                ('enterpreneur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.enterpreneur')),
            ],
        ),
    ]
