# Generated by Django 5.2.1 on 2025-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photoname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
