# Generated by Django 5.2.1 on 2025-08-05 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_company_created_at_company_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, default='Россия', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterpreneur',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enterpreneur',
            name='fathername',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enterpreneur',
            name='phone',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enterpreneur',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='photoname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='twogislink',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.city'),
        ),
    ]
